### ISSUE TITLE
Did they change the API again?

### ISSUE THREAD

**Issue by Heliuum** [xurei/twitch-highlights-logger#10]
Latest release: v0.3.1 vs 0.3.1
FETCHING...
{ error: 'Not Found', status: 404, message: 'This API does not exist' }
Fetching at null
ERROR LOADING CHATLOG
Sending logs to main view

**Comment by Heliuum** [comment]
OS: Windows

**Comment by xurei** [comment]
I actually forgot to migrate an API call from Kraken :sweat_smile: 

I have a fix and a new version curently building. This should be solved in a few hours max.

BTW, thank you :heart:

**Comment by Heliuum** [comment]
o7

**Comment by xurei** [comment]
Here it is !
https://github.com/xurei/twitch-highlights-logger/releases/tag/v0.3.2
