### ISSUE TITLE
 "An error occurred while fetching the chatlog."

### ISSUE THREAD

**Issue by Heliuum** [xurei/twitch-highlights-logger#13]
- Operating system:  Windows
- App version: 0.3.2

"An error occurred while fetching the chatlog."
![image](https://user-images.githubusercontent.com/38300235/236299501-142637f8-75b9-4644-9554-f16714a75b6f.png)

**Comment by Heliuum** [comment]
Did they change API again?

**Comment by Heliuum** [comment]
The problem is still present. Reinstallation didnt help

**Comment by xurei** [comment]
I'm on it ! 
Twitch has changed the API recently. I found a patch, I'll create an update in a few hours.

**Comment by Heliuum** [comment]
LEGEND! Thank you!
