### ISSUE TITLE
Problème de lecture en mode PAUSE.

### ISSUE THREAD

**Issue by Copainduweb** [xurei/twitch-highlights-logger#2]
- Operating system: Windows 10
- App version: 0.0.6

Quand la lecture est sur PAUSE il n'est pas possible de passer à un autre Timecode en cliquant dessus. il faut relancer la lecture et ça fonctionne.

**Comment by xurei** [comment]
Solved by e3cd86af9a9d4edb3e4f03985ead7a73d6c7df9a in v0.0.7
