### ISSUE TITLE
Seems to be broken on both windows and linux

### ISSUE THREAD

**Issue by Heliuum** [xurei/twitch-highlights-logger#8]
Tried on Ubuntu in Vbox and on windows. 
On both systems "Loading chatlog" stays on 0%

![image](https://user-images.githubusercontent.com/38300235/206285486-056aa89a-7f7c-428c-b1ca-900327fabd02.png)
here screenshot from ubuntu terminal

**Comment by xurei** [comment]
This is due to an API change from Twitch.

I'm currently working on it. A new release will be available in a few days (if not today).

**Comment by xurei** [comment]
A new release fixing this is out !

https://github.com/xurei/twitch-highlights-logger/releases/tag/v0.3.0
